// Generated by CoffeeScript 1.3.3
(function() {
  var get_check_code;

  get_check_code = function() {
    return $.get("http://check.ptlogin2.qq.com/check?uin=leafduo@gmail.com&appid=567008010&r=0.8911660050507635", function(data) {
      data = data.toString();
      return $(data).appendTo('#info');
    });
  };

  get_check_code();

}).call(this);
